/**
 * Wheel copy from docs/product/copy-deck.md (local constants).
 */

export const WHEEL_COPY = {
  templateName: "Spin the wheel",
  templateDescription:
    "Spin to pick a random item from your list—great for names, topics, or prompts.",
  templateShort: "Wheel",
  bulkHelp: "One item per line",
  limits: "2–100 items. Labels get hard to read above 30.",
  warnMany: "You have more than 30 items. Consider shortening labels.",
  valMinItems: "Add at least 2 items.",
  valItemEmpty: "This item needs text or an image.",
  settingsSpinPower: "Spin power",
  settingsSpinPowerLow: "Low",
  settingsSpinPowerMedium: "Medium",
  settingsSpinPowerHigh: "High",
  settingsAllowEliminate: "Allow eliminate",
  settingsShuffleItems: "Shuffle items",
  settingsImageDisplay: "Images on wheel",
  intro: "Press Spin and see where the wheel lands.",
  spin: "Spin",
  spinAgain: "Spin again",
  eliminate: "Eliminate",
  resume: "Resume",
  complete: "Only one item left. Reset to play again.",
  reset: "Reset wheel",
  resultSummary: "Items selected this session",
  noLeaderboard: "This activity has no score or leaderboard.",
  instructionLabel: "Instruction (optional)",
  addItem: "Add an item",
  bulkPaste: "Bulk paste",
  bulkPastePlaceholder: "Paste one item per line…",
  applyBulk: "Add lines",
  cancelBulk: "Cancel",
  duplicate: "Duplicate",
  delete: "Delete",
  moveUp: "Move up",
  moveDown: "Move down",
  itemLabel: "Item",
  selectedAnnounce: (label: string) => `Selected: ${label}`,
  completeAnnounce: (label: string) => `Complete. Last item: ${label}`,
} as const;
