/**
 * Wordsearch copy from docs/product/copy-deck.md (local constants).
 */

export const WORDSEARCH_COPY = {
  templateName: "Wordsearch",
  templateDescription:
    "Hide words in a letter grid; players hunt by drag or tap.",
  templateShort: "Wordsearch",
  limits: "2–40 words. 6–16 is a good classroom length.",
  warnMany: "You have more than 16 words. Placement may take longer.",
  valMin: "Add at least 2 words.",
  valDuplicate: (word: string) =>
    `“${word}” matches another word after normalization.`,
  valCharset: (word: string) =>
    `“${word}” has characters this grid cannot use.`,
  valTooLong: (word: string) => `“${word}” is too long for the grid.`,
  valEmpty: "Enter a word.",
  valShort: (word: string) => `“${word}” needs at least 2 letters for the grid.`,
  valPlacement: (words: string) =>
    `Could not place every word. Try shorter words or turn on more directions: ${words}.`,
  bulkHelp: "One word per line, or word then tab then clue",
  bulkPaste: "Bulk paste",
  bulkPastePlaceholder: "Paste one word per line (or word → tab → clue)…",
  applyBulk: "Add lines",
  cancelBulk: "Cancel",
  addWord: "Add a word",
  duplicate: "Duplicate",
  delete: "Delete",
  moveUp: "Move up",
  moveDown: "Move down",
  wordLabel: "Word",
  normalizedLabel: "Grid letters",
  clueLabel: "Clue (optional)",
  clueMode: "Words with clues",
  wordsOnlyMode: "Words only",
  intro: "Find every hidden word in the grid.",
  found: (word: string) => `Found: ${word}`,
  wordsLeft: (count: number) =>
    count === 1 ? "1 word left" : `${count} words left`,
  complete: "You found every word!",
  gameOver: "Out of lives. Review the answers.",
  livesLeft: (n: number) => (n === 1 ? "1 life left" : `${n} lives left`),
  wordList: "Word list",
  missed: "Missed words",
  foundList: "Found words",
  startKeyboard: "Keyboard: focus a cell, press Enter to start, arrow keys to extend, Enter to confirm.",
  settingsDiagonal: "Allow diagonal",
  settingsReverse: "Allow reverse",
  settingsShowList: "Show word list",
  settingsSelectionMode: "Selection mode",
  settingsSelectionDrag: "Drag full word",
  settingsSelectionTapFirst: "Tap first letter",
  settingsSelectionTapAny: "Tap any letter",
  settingsLetterCase: "Letter case",
  settingsShowAnswers: "Show answers at end",
  settingsDiacritic: "Diacritics",
  settingsDiacriticFold: "Fold accents for the grid",
  settingsDiacriticRetain: "Keep accents when possible",
  settingsLives: "Lives",
  settingsTimer: "Timer",
  reset: "Play again",
  scoreLabel: "Words found",
} as const;
