/**
 * True/False copy from docs/product/copy-deck.md (local constants).
 */

export const TRUE_FALSE_COPY = {
  templateName: "True or false",
  templateDescription:
    "Decide whether each statement is true or false before time runs out.",
  templateShort: "True or false",
  limits: "2–100 statements. Each must be marked true or false.",
  warnImbalance: (dominant: "true" | "false") =>
    `This set is mostly ${dominant}. Players may learn the pattern.`,
  valMinStatements: "Add at least 2 statements.",
  valTruthRequired: "Choose True or False for this statement.",
  valStatementEmpty: "Add statement text or an image.",
  valMaxStatements: "At most 100 statements are allowed.",
  instructionLabel: "Instruction (optional)",
  addStatement: "Add a statement",
  bulkPaste: "Bulk paste",
  bulkPasteHelp:
    "One statement per line. End with [T] or [F] for truth (default True).",
  bulkPastePlaceholder: "Earth orbits the Sun [T]\nThe Moon is a star [F]",
  applyBulk: "Add lines",
  cancelBulk: "Cancel",
  duplicate: "Duplicate",
  delete: "Delete",
  moveUp: "Move up",
  moveDown: "Move down",
  statementLabel: "Statement",
  markTrue: "True",
  markFalse: "False",
  truthToggleLabel: "Truth value",
  settingsSpeed: "Speed",
  settingsLives: "Lives",
  settingsLivesUnlimited: "Unlimited",
  settingsRepeatUntilTime: "Repeat until time runs out",
  settingsShowAnswers: "Show answers at end",
  settingsShuffle: "Shuffle statements",
  settingsTimer: "Timer",
  intro: "Choose True or False for each statement.",
  trueButton: "True",
  falseButton: "False",
  correct: "Correct",
  incorrect: "Incorrect",
  expired: "Time's up",
  gameOver: "Game over",
  complete: "Complete!",
  livesRemaining: (n: number) => (n === 1 ? "1 life left" : `${n} lives left`),
  progress: (current: number, total: number) => `${current} / ${total}`,
  correctAnnounce: "Correct",
  incorrectAnnounce: "Incorrect",
  expiredAnnounce: "Time ran out",
  completeAnnounce: (score: number) => `Complete. Score ${score}`,
  gameOverAnnounce: (score: number) => `Game over. Score ${score}`,
  reviewTitle: "Review answers",
  start: "Start",
  next: "Next",
} as const;
