/**
 * Image quiz copy from docs/product/copy-deck.md (local constants).
 */

export const IMAGE_QUIZ_COPY = {
  templateName: "Image quiz",
  templateDescription:
    "Reveal a picture tile by tile, then buzz in to answer.",
  templateShort: "Image quiz",
  limits: "1–100 questions. Each needs a reveal image and 2–6 answers.",
  valMinQuestions: "Add at least 1 question.",
  valRevealRequired: "Add a reveal image for this question.",
  valRevealAlt: "Describe this image for accessibility.",
  valAnswers: "Each question needs 2 to 6 answers and one correct answer.",
  valCorrectRequired: "Mark one correct answer.",
  valPromptEmpty: "Add question text or an image (recommended).",
  intro: "Watch the image appear, buzz in, then choose your answer.",
  buzzer: "Buzzer",
  buzzHint: "Press Buzzer or Space when you know it",
  loadingImage: "Loading image…",
  imageError: "This image could not be loaded. Try again or repair the activity.",
  retryImage: "Retry image",
  continue: "Continue",
  correct: "Correct",
  incorrect: "Incorrect",
  unanswered: "No answer",
  complete: "Nice work!",
  gameOver: "Game over",
  addQuestion: "Add a question",
  addAnswer: "Add an answer",
  deleteQuestion: "Delete question",
  deleteAnswer: "Delete answer",
  duplicateQuestion: "Duplicate question",
  moveUp: "Move up",
  moveDown: "Move down",
  markCorrect: "Correct answer",
  questionLabel: "Question",
  answerLabel: "Answer",
  promptLabel: "Prompt (optional)",
  revealImageLabel: "Reveal image (required)",
  chooseRevealImage: "Choose reveal image",
  changeRevealImage: "Change reveal image",
  removeRevealImage: "Remove reveal image",
  revealImageAltLabel: "Image description",
  answersLabel: "Answers",
  settingsRevealDuration: "Reveal duration",
  settingsBasePoints: "Base points",
  settingsLives: "Lives",
  settingsLivesUnlimited: "Unlimited",
  settingsShuffle: "Shuffle questions",
  settingsAutoProceed: "Auto-proceed after feedback",
  settingsShowAnswers: "Show answers at end",
  settingsLayout: "Layout",
  settingsLayoutTogether: "Image and answers together",
  settingsLayoutSeparate: "Image then answers",
  scoreLabel: "Score",
  livesLabel: "Lives",
  progressLabel: (current: number, total: number) =>
    `${current} of ${total}`,
  pointsAwarded: (n: number) => `+${n} points`,
  buzzAnnounce: "Buzzed in. Choose your answer.",
  fullRevealAnnounce: "Image fully revealed. Choose your answer.",
  correctAnnounce: (points: number) => `Correct. Plus ${points} points.`,
  incorrectAnnounce: "Incorrect.",
  gameOverAnnounce: "Game over. No lives remaining.",
  completeAnnounce: (score: number) => `Complete. Score ${score}.`,
} as const;
